config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'mental_health', to: 'pages#mental_health', as: :mental_health
  get 'about_us', to: 'pages#about_us', as: :about_us

  resources :subforums do
    collection do
      get 'search', to: 'subforums#search'
    end
    resources :posts, only: %i[show new create edit update destroy] do
      resources :comments, only: %i[create destroy]
    end
  end
  resources :calls
  resources :journals

  resources :users, only: %i[show]
  patch '/users/:id/online_status', to: 'users#online_status', as: :update_online_status

  resources :livechats, only: %i[index show create update destroy] do
    resources :messages, only: %i[index create]
  end
  get 'subforums/posts', to: 'posts#all_posts', as: 'all_subforum_posts'
end

app/models/subforum.rb
class Subforum < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/subforums_controller.rb
class SubforumsController < ApplicationController
  before_action :set_subforum, only: %i[show edit update destroy]

  def index
    authorize Subforum
    @subforums = policy_scope(Subforum)

    if params[:query].present?
      @posts = Post.search_by_title_and_content(params[:query])
    else
      @posts = Post.all
    end
  end

  def show
    authorize @subforum
    @posts = @subforum.posts.includes(:comments)
  end

  def new
    @subforum = Subforum.new
    authorize @subforum
  end

  def create
    @subforum = Subforum.new(subforum_params)
    authorize @subforum
    if @subforum.save
      redirect_to subforum_path(@subforum)
    else
      render :new, status: :unprocessable
    end
  end

  def edit
    authorize @subforum
  end

  def update
    authorize @subforum
    if @subforum.update(subforum_params)
      redirect_to subforum_path(@subforum)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @subforum
    @subforum.destroy
    redirect_to subforums_path
  end

  def search
    authorize Subforum, :index?
    @subforums = policy_scope(Subforum)
    @posts = Post.search_by_title_and_content(params[:query])
    render :index
  end

  private

  def subforum_params
    params.require(:subforum).permit(:name, :description, :photo)
  end

  def set_subforum
    @subforum = Subforum.find(params[:id])
  end
end

app/views/subforums/_form.html.erb
<%= simple_form_for @subforum do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end  %>

app/views/subforums/edit.html.erb
<%= render "form" %>

app/views/subforums/index.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- Search Form -->
    <%= form_with url: search_subforums_path, method: :get, local: true do %>
      <div class="input-group mb-3">
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search for posts" %>
        <div class="input-group-append">
          <%= submit_tag "Search", class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>

    <!-- Sidebar -->
    <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <h2 class="sidebar-heading">Subforums</h2>
        <ul class="nav flex-column">
          <% @subforums.each do |subforum| %>
            <li class="nav-item">
              <%= link_to subforum.name, subforum_path(subforum), class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <%= link_to "New Subforum", new_subforum_path, class: "btn btn-primary mt-3" %>
      </div>
    </nav>

    <!-- Main Content -->
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Recent Posts</h1>
      </div>
      <div class="posts-list">
        <% @posts.each do |post| %>
          <div class="post mb-4">
            <div class="post-files mb-2">
              <% post.files.each do |file| %>
                <% if file.content_type.start_with?('image/') %>
                  <%= cl_image_tag file.key, class: 'post-image' %>
                <% elsif file.content_type.start_with?('video/') %>
                  <%= cl_video_tag file.key, controls: true, class: 'post-video' %>
                <% else %>
                  <%= link_to file.filename.to_s, url_for(file), class: 'post-file' %>
                <% end %>
              <% end %>
            </div>
            <h3><%= link_to post.title, subforum_post_path(post.subforum, post), class: "text-dark" %></h3>
            <p><%= truncate(post.content, length: 200) %></p>
            <span class="badge <%= random_badge_color %>">
              Posted by <%= post.user.email %> in <%= link_to post.subforum.name, subforum_path(post.subforum), class: "text-white" %>
            </span>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/subforums/new.html.erb
<%= render "form" %>

app/views/subforums/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <div class="d-flex justify-content-between align-items-center">
        <h1 class="display-4"><%= @subforum.name %></h1>
        <%= link_to "Create New Post", new_subforum_post_path(@subforum), class: "btn btn-success mt-4" %>
      </div>
      <p class="lead"><%= @subforum.description %></p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-12">
      <h2>Posts</h2>
      <div class="posts-list">
        <% @posts.each do |post| %>
          <div class="post">
            <div class="post-header d-flex justify-content-between align-items-center">
              <h3><%= link_to post.title, subforum_post_path(@subforum, post), class: "text-dark" %></h3>
              <span class="timestamp">Posted by <%= post.user.email %> on <%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
            </div>
            <p><%= truncate(post.content, length: 150) %></p>

            <div class="comment-section mt-4">
              <% if post.comments.any? %>
                <h4>Comments</h4>
                <ul class="list-unstyled">
                  <% post.comments.each do |comment| %>
                    <li class="comment p-3 mb-3">
                      <p><strong><%= comment.user.email %>:</strong> <%= comment.body %></p>
                      <p class="timestamp">Posted on <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
                    </li>
                  <% end %>
                </ul>
              <% else %>
                <p>No comments yet.</p>
              <% end %>
              <h4>Add a Comment</h4>
              <%= simple_form_for([post.subforum, post, Comment.new], url: subforum_post_comments_path(post.subforum, post), local: true) do |form| %>
                <div class="form-group">
                  <%= form.input :body, as: :text, label: "Your Comment", input_html: { rows: 3, class: "form-control" } %>
                </div>
                <div class="form-group">
                  <%= form.button :submit, "Add Comment", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="m-4">
    <%= link_to "Back to Subforums", subforums_path, class: "btn btn-primary me-2" %>
    <%= link_to "Edit Subforum", edit_subforum_path(@subforum), class: "btn btn-secondary me-2" %>
    <%= link_to "Delete Subforum", subforum_path(@subforum), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
  </div>
</div>