config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'mental_health', to: 'pages#mental_health', as: :mental_health
  get 'about_us', to: 'pages#about_us', as: :about_us

  resources :subforums do
    collection do
      get 'search', to: 'subforums#search'
    end
    resources :posts, only: %i[show new create edit update destroy] do
      resources :comments, only: %i[create destroy]
    end
  end
  resources :calls
  resources :journals

  resources :users, only: %i[show]
  patch '/users/:id/online_status', to: 'users#online_status', as: :update_online_status

  resources :livechats, only: %i[index show create update destroy] do
    resources :messages, only: %i[index create]
  end
  get 'subforums/posts', to: 'posts#all_posts', as: 'all_subforum_posts'
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def index
    @journals = policy_scope(Journal).order(created_at: :desc)
    authorize Journal
  end

  def show
    @journal = Journal.find(params[:id])
    authorize @journal
  end

  def new
    @journal = Journal.new
    authorize @journal
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.user = current_user
    authorize @journal
    if @journal.save
      redirect_to journals_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @journal = Journal.find(params[:id])
    authorize @journal
  end

  def update
    @journal = Journal.find(params[:id])
    authorize @journal
    if @journal.update(journal_params)
      redirect_to journals_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @journal = Journal.find(params[:id])
    authorize @journal
    @journal.destroy
    redirect_to journals_path, status: :see_other
  end

  private

  def journal_params
    params.require(:journal).permit(:title, :content)
  end
end

app/views/journals/edit.html.erb
<%= simple_form_for @journal do |f|%>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/journals/index.html.erb
<div class="journals-wrapper">
  <div class="journals-header">
    <h1>Journal Entries</h1>
    <%= link_to "Add Entry", new_journal_path, class: "btn btn-primary"%>
  </div>
  <div class="journals-items">
  <% @journals.each do |journal| %>
    <div class="journal-item">
      <h2><%= link_to journal.title, journal_path(journal)%></h2>
      <p class="journal-item-date"><%= journal.created_at.strftime("%B %d, %Y") %></p>
      <div class="journal-item-content">
        <p><%= journal.content %></p>
      </div>

    </div>
  <% end %>


  </div>
</div>


<br>
<br>
<%= link_to "Back to Dashboard", dashboard_path%>

app/views/journals/new.html.erb
<div class="journals-wrapper">
  <h1>Add Journal Entry</h1>

  <%= simple_form_for @journal do |f|%>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit "Add entry", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/journals/show.html.erb
<div class="journals-wrapper">
  <h2><%= link_to @journal.title, journal_path(@journal)%></h2>
  <p class="journal-item-date"><%= @journal.created_at.strftime("%B %d, %Y") %></p>
  <div class="journal-item-content">
    <p><%= @journal.content %></p>
  </div>
  <%= link_to "Volver", journals_path%>
</div>